# Generated by Django 5.2 on 2025-04-12 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleve",
            name="type_permis",
            field=models.CharField(
                choices=[("manuel", "Manuel"), ("auto", "Auto")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="vehicule",
            name="type_vehicule",
            field=models.CharField(
                choices=[("manuel", "Manuel"), ("auto", "Auto")], max_length=50
            ),
        ),
        migrations.CreateModel(
            name="MoniteurNonDisponibilite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField()),
                ("motif", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "moniteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.moniteur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiculeNonDisponibilite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField()),
                ("motif", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.vehicule",
                    ),
                ),
            ],
        ),
    ]
